<a href="https://colab.research.google.com/github/MohdAffan27/AI-Learning-Journey/blob/main/03_PANDAS/PandasTutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Pandas
Pandas(stands for Python Data Analysis) is a powerful, open-source Python library used for data manipulation, analysis, and cleaning.

* Think of it as Microsoft Excel or Google Sheets, but built entirely inside Python code.

### -> Revolves around two primary Data structures:
* Series (1D)
* DataFrame (2D)

### -> What is Pandas Used for?
* Reading and writing data from various file formats like CSV, Excel and SQL databases.
* Cleaning and preparing data (handling missing values, filtering, removing duplicates).
* Merging, joining, and reshaping datasets.
* Performing statistical analysis and descriptive statistics.
* Visualizing data quickly.

In [73]:
import pandas as pd

1. Pandas Series

          A Pandas Series is a one-dimensional labeled array capable of holding data of any type. It can be created from Python lists, NumPy arrays, dictionaries, scalar values or data loaded from external sources such as CSV files, Excel files and databases. The labels associated with a Series are called its index.

In [74]:
s = pd.Series([1,2,3,4,5])

In [75]:
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

2. Pandas DataFrame

        Pandas DataFrame is a two-dimensional data structure with labeled axes (rows and columns). It is created by loading the datasets from existing storage which can be a SQL database, a CSV file or an Excel file. It can be created from lists, dictionaries, a list of dictionaries etc.

In [76]:
df = pd.DataFrame({'Name': ['Mohammed Affan', 'Mohammed Faizaan Ali Khan', 'Shaik Sahil'],
                   'Age': [19, 20, 22],
                   'City': ['Bodhan', 'Auto Nagar', 'Nizam Colony']})

### -> Operations in Pandas
Pandas provides essential operations for working with structured data efficiently. The sections below introduce the most commonly used functionalities with short explanations and simple examples.

1. Loading Data:

          This operation reads data from files such as CSV, Excel or JSON into a DataFrame.

In [77]:
df = pd.read_excel("/content/sample_data/FSI-2023-DOWNLOAD.xlsx")

In [78]:
df

,Country,Year,Rank,Total,S1: Demographic Pressures,S2: Refugees and IDPs,C3: Group Grievance,E3: Human Flight and Brain Drain,E2: Economic Inequality,E1: Economy,P1: State Legitimacy,P2: Public Services,P3: Human Rights,C1: Security Apparatus,C2: Factionalized Elites,X1: External Intervention
0,Somalia,2023,1st,111.9,10.0,9.0,8.7,8.6,9.1,9.5,9.6,9.8,9.0,9.5,10.0,9.1
1,Yemen,2023,2nd,108.9,9.6,9.6,8.8,6.4,7.9,9.9,9.8,9.6,9.6,8.6,9.9,9.2
2,South Sudan,2023,3rd,108.5,9.7,10.0,8.6,6.5,8.6,8.6,9.8,9.7,8.7,9.9,9.2,9.2
3,Congo Democratic Republic,2023,4th,107.2,9.7,9.8,9.4,6.4,8.4,8.1,9.3,9.3,9.3,8.8,9.6,9.1
4,Syria,2023,5th,107.1,7.4,9.1,9.1,8.0,6.5,9.6,10.0,9.0,9.1,9.4,9.9,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
174,Switzerland,2023,175th,17.8,2.4,3.2,2.1,1.0,2.4,1.6,0.3,1.6,0.4,1.4,1.0,0.4
175,New Zealand,2023,176th,16.7,1.1,1.2,2.0,1.6,2.6,2.6,0.5,1.1,0.5,1.6,1.4,0.5
176,Finland,2023,177th,16.0,1.7,1.9,0.3,1.5,1.6,2.7,0.4,1.0,0.5,2.0,1.4,1.0
177,Iceland,2023,178th,15.7,1.5,1.5,0.5,1.6,1.5,2.6,0.4,0.9,0.4,0.4,1.8,2.6
178,Norway,2023,179th,14.5,1.4,1.7,3.1,0.7,1.4,1.4,0.4,1.0,0.4,1.4,1.1,0.5

2. Viewing and Exploring Data:

          After loading data, it is important to understand its structure and content. This methods allow you to inspect rows, summary statistics and metadata.

In [79]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 179 entries, 0 to 178
Data columns (total 16 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Country                           179 non-null    object
 1   Year                              179 non-null    int64
 2   Rank                              179 non-null    object
 3   Total                             179 non-null    float64
 4   S1: Demographic Pressures         179 non-null    float64
 5   S2: Refugees and IDPs             179 non-null    float64
 6   C3: Group Grievance               179 non-null    float64
 7   E3: Human Flight and Brain Drain  179 non-null    float64
 8   E2: Economic Inequality           179 non-null    float64
 9   E1: Economy                       179 non-null    float64
 10  P1: State Legitimacy              179 non-null    float64
 11  P2: Public Services               179 non-null    float64
 12  P3: Human Rights                  179 non-null    float64
 13  C1: Security Apparatus            179 non-null    float64
 14  C2: Factionalized Elites          179 non-null    float64
 15  X1: External Intervention         179 non-null    float64
dtypes: float64(13), int64(1), object(2)
memory usage: 22.5+ KB

3. Describe() in pandas

          In Python's Pandas library, the DataFrame.describe() method is a tool used to generate a quick descriptive summary statistics overview of your data.

In [80]:
df.describe()

,Year,Total,S1: Demographic Pressures,S2: Refugees and IDPs,C3: Group Grievance,E3: Human Flight and Brain Drain,E2: Economic Inequality,E1: Economy,P1: State Legitimacy,P2: Public Services,P3: Human Rights,C1: Security Apparatus,C2: Factionalized Elites,X1: External Intervention
count,179.0,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000,179.000000
mean,2023.0,65.832402,5.955866,4.764246,5.574860,5.184358,5.323464,5.687151,5.741341,5.459218,5.436872,5.014525,6.618436,5.072067
std,0.0,23.966251,2.278726,2.373935,2.367757,2.079591,2.068546,2.200741,2.901853,2.581299,2.602588,2.379810,2.427869,2.577801
min,2023.0,14.500000,1.100000,0.500000,0.300000,0.400000,1.400000,1.000000,0.300000,0.900000,0.400000,0.300000,1.000000,0.300000
25%,2023.0,49.000000,4.100000,2.800000,3.600000,3.700000,3.650000,4.100000,3.650000,3.450000,3.600000,3.350000,4.950000,3.150000
50%,2023.0,68.200000,5.900000,4.500000,5.500000,5.600000,5.200000,6.000000,6.400000,5.100000,5.700000,5.100000,7.200000,5.300000
75%,2023.0,82.200000,8.050000,6.450000,7.550000,6.600000,7.200000,7.150000,8.100000,7.950000,7.500000,6.700000,8.550000,7.000000
max,2023.0,111.900000,10.000000,10.000000,9.700000,10.000000,9.600000,9.900000,10.000000,10.000000,9.900000,10.000000,10.000000,10.000000

4. head() in Pandas used to print starting 5 records from the given list

In [81]:
df.head()

,Country,Year,Rank,Total,S1: Demographic Pressures,S2: Refugees and IDPs,C3: Group Grievance,E3: Human Flight and Brain Drain,E2: Economic Inequality,E1: Economy,P1: State Legitimacy,P2: Public Services,P3: Human Rights,C1: Security Apparatus,C2: Factionalized Elites,X1: External Intervention
0,Somalia,2023,1st,111.9,10.0,9.0,8.7,8.6,9.1,9.5,9.6,9.8,9.0,9.5,10.0,9.1
1,Yemen,2023,2nd,108.9,9.6,9.6,8.8,6.4,7.9,9.9,9.8,9.6,9.6,8.6,9.9,9.2
2,South Sudan,2023,3rd,108.5,9.7,10.0,8.6,6.5,8.6,8.6,9.8,9.7,8.7,9.9,9.2,9.2
3,Congo Democratic Republic,2023,4th,107.2,9.7,9.8,9.4,6.4,8.4,8.1,9.3,9.3,9.3,8.8,9.6,9.1
4,Syria,2023,5th,107.1,7.4,9.1,9.1,8.0,6.5,9.6,10.0,9.0,9.1,9.4,9.9,10.0

4. tail() in Pandas used to print Last 5 records from the given list

In [82]:
df.tail()

,Country,Year,Rank,Total,S1: Demographic Pressures,S2: Refugees and IDPs,C3: Group Grievance,E3: Human Flight and Brain Drain,E2: Economic Inequality,E1: Economy,P1: State Legitimacy,P2: Public Services,P3: Human Rights,C1: Security Apparatus,C2: Factionalized Elites,X1: External Intervention
174,Switzerland,2023,175th,17.8,2.4,3.2,2.1,1.0,2.4,1.6,0.3,1.6,0.4,1.4,1.0,0.4
175,New Zealand,2023,176th,16.7,1.1,1.2,2.0,1.6,2.6,2.6,0.5,1.1,0.5,1.6,1.4,0.5
176,Finland,2023,177th,16.0,1.7,1.9,0.3,1.5,1.6,2.7,0.4,1.0,0.5,2.0,1.4,1.0
177,Iceland,2023,178th,15.7,1.5,1.5,0.5,1.6,1.5,2.6,0.4,0.9,0.4,0.4,1.8,2.6
178,Norway,2023,179th,14.5,1.4,1.7,3.1,0.7,1.4,1.4,0.4,1.0,0.4,1.4,1.1,0.5

### -> Data Selection

##### 1. 1D (series)

In [84]:
df["Country"] #1D (series)

0                        Somalia
1                          Yemen
2                    South Sudan
3      Congo Democratic Republic
4                          Syria
                 ...
174                  Switzerland
175                  New Zealand
176                      Finland
177                      Iceland
178                       Norway
Name: Country, Length: 179, dtype: object

##### 2. 2D (Data frames)

In [86]:
df[["Country","Rank"]]

                       Country   Rank
0                      Somalia    1st
1                        Yemen    2nd
2                  South Sudan    3rd
3    Congo Democratic Republic    4th
4                        Syria    5th
..                         ...    ...
174                Switzerland  175th
175                New Zealand  176th
176                    Finland  177th
177                    Iceland  178th
178                     Norway  179th

[179 rows x 2 columns]

##### 3. iloc(index no.)

In [89]:
df.iloc[8]

Country                              Chad
Year                                 2023
Rank                                  9th
Total                               104.6
S1: Demographic Pressures             9.5
S2: Refugees and IDPs                 9.0
C3: Group Grievance                   8.1
E3: Human Flight and Brain Drain      7.7
E2: Economic Inequality               8.7
E1: Economy                           8.4
P1: State Legitimacy                  9.1
P2: Public Services                   9.6
P3: Human Rights                      8.4
C1: Security Apparatus                8.7
C2: Factionalized Elites              9.5
X1: External Intervention             7.9
Name: 8, dtype: object

### -> Handling Missing values

In [91]:
df2 = pd.read_excel("/content/sample_data/Data.xlsx")

In [92]:
df2

   User_ID            Name   Age   Join_Date  Monthly_Spend Premium_Member
0     1001     Alice Smith  28.0  2024-01-15          145.2            Yes
1     1002       Bob Jones   NaN  2023-11-22           89.5             No
2     1003   Charlie Brown  42.0  2025-03-05            NaN            Yes
3     1004    David Miller  31.0         NaN          210.0             No
4     1005       Eva Davis   NaN  2024-06-18           55.0            NaN
5     1006    Frank Wilson  55.0  2022-08-30          415.8            Yes
6     1007       Grace Lee  23.0  2025-01-12            NaN             No
7     1008    Henry Taylor   NaN         NaN          125.0             No
8     1009  Isabella Clark  38.0  2023-05-19          305.1            Yes
9     1010     Jack Thomas  47.0  2024-10-01            NaN            NaN

1. Remove all Missing values

In [93]:
df2.dropna()

   User_ID            Name   Age   Join_Date  Monthly_Spend Premium_Member
0     1001     Alice Smith  28.0  2024-01-15          145.2            Yes
5     1006    Frank Wilson  55.0  2022-08-30          415.8            Yes
8     1009  Isabella Clark  38.0  2023-05-19          305.1            Yes

2. Replace Missing values

In [94]:
df2.fillna(value=0)

   User_ID            Name   Age   Join_Date  Monthly_Spend Premium_Member
0     1001     Alice Smith  28.0  2024-01-15          145.2            Yes
1     1002       Bob Jones   0.0  2023-11-22           89.5             No
2     1003   Charlie Brown  42.0  2025-03-05            0.0            Yes
3     1004    David Miller  31.0           0          210.0             No
4     1005       Eva Davis   0.0  2024-06-18           55.0              0
5     1006    Frank Wilson  55.0  2022-08-30          415.8            Yes
6     1007       Grace Lee  23.0  2025-01-12            0.0             No
7     1008    Henry Taylor   0.0           0          125.0             No
8     1009  Isabella Clark  38.0  2023-05-19          305.1            Yes
9     1010     Jack Thomas  47.0  2024-10-01            0.0              0

3. Rename Column Name

In [101]:
df2.rename(columns={"n":"Name", "Join_Date":"JD","Monthly_Spend":"MD"}, inplace=True)
df2

   User_ID            name   Age          JD     MD Premium_Member
0     1001     Alice Smith  28.0  2024-01-15  145.2            Yes
1     1002       Bob Jones   NaN  2023-11-22   89.5             No
2     1003   Charlie Brown  42.0  2025-03-05    NaN            Yes
3     1004    David Miller  31.0         NaN  210.0             No
4     1005       Eva Davis   NaN  2024-06-18   55.0            NaN
5     1006    Frank Wilson  55.0  2022-08-30  415.8            Yes
6     1007       Grace Lee  23.0  2025-01-12    NaN             No
7     1008    Henry Taylor   NaN         NaN  125.0             No
8     1009  Isabella Clark  38.0  2023-05-19  305.1            Yes
9     1010     Jack Thomas  47.0  2024-10-01    NaN            NaN