<a href="https://colab.research.google.com/github/MohdAffan27/AI-Learning-Journey/blob/main/03_PANDAS/PandasTutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Pandas
Pandas(stands for Python Data Analysis) is a powerful, open-source Python library used for data manipulation, analysis, and cleaning.

* Think of it as Microsoft Excel or Google Sheets, but built entirely inside Python code.

### -> Revolves around two primary Data structures:
* Series (1D)
* DataFrame (2D)

### -> What is Pandas Used for?
* Reading and writing data from various file formats like CSV, Excel and SQL databases.
* Cleaning and preparing data (handling missing values, filtering, removing duplicates).
* Merging, joining, and reshaping datasets.
* Performing statistical analysis and descriptive statistics.
* Visualizing data quickly.

In [71]:
import pandas as pd

1. Pandas Series

          A Pandas Series is a one-dimensional labeled array capable of holding data of any type. It can be created from Python lists, NumPy arrays, dictionaries, scalar values or data loaded from external sources such as CSV files, Excel files and databases. The labels associated with a Series are called its index.

In [72]:
s = pd.Series([1,2,3,4,5])

In [73]:
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

2. Pandas DataFrame

        Pandas DataFrame is a two-dimensional data structure with labeled axes (rows and columns). It is created by loading the datasets from existing storage which can be a SQL database, a CSV file or an Excel file. It can be created from lists, dictionaries, a list of dictionaries etc.

In [74]:
df = pd.DataFrame({'Name': ['Mohammed Affan', 'Mohammed Faizaan Ali Khan', 'Shaik Sahil'],
                   'Age': [19, 20, 22],
                   'City': ['Bodhan', 'Auto Nagar', 'Nizam Colony']})

### -> Operations in Pandas
Pandas provides essential operations for working with structured data efficiently. The sections below introduce the most commonly used functionalities with short explanations and simple examples.

1. Loading Data:

          This operation reads data from files such as CSV, Excel or JSON into a DataFrame.

In [75]:
df = pd.read_csv("/content/sample_data/california_housing_test.csv")

In [76]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

2. Viewing and Exploring Data:

          After loading data, it is important to understand its structure and content. This methods allow you to inspect rows, summary statistics and metadata.

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           3000 non-null   float64
 1   latitude            3000 non-null   float64
 2   housing_median_age  3000 non-null   float64
 3   total_rooms         3000 non-null   float64
 4   total_bedrooms      3000 non-null   float64
 5   population          3000 non-null   float64
 6   households          3000 non-null   float64
 7   median_income       3000 non-null   float64
 8   median_house_value  3000 non-null   float64
dtypes: float64(9)
memory usage: 211.1 KB

3. Describe() in pandas

          In Python's Pandas library, the DataFrame.describe() method is a tool used to generate a quick descriptive summary statistics overview of your data.

In [78]:
df.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,3000.000000,3000.00000,3000.000000,3000.000000,3000.000000,3000.000000,3000.00000,3000.000000,3000.00000
mean,-119.589200,35.63539,28.845333,2599.578667,529.950667,1402.798667,489.91200,3.807272,205846.27500
std,1.994936,2.12967,12.555396,2155.593332,415.654368,1030.543012,365.42271,1.854512,113119.68747
min,-124.180000,32.56000,1.000000,6.000000,2.000000,5.000000,2.00000,0.499900,22500.00000
25%,-121.810000,33.93000,18.000000,1401.000000,291.000000,780.000000,273.00000,2.544000,121200.00000
50%,-118.485000,34.27000,29.000000,2106.000000,437.000000,1155.000000,409.50000,3.487150,177650.00000
75%,-118.020000,37.69000,37.000000,3129.000000,636.000000,1742.750000,597.25000,4.656475,263975.00000
max,-114.490000,41.92000,52.000000,30450.000000,5419.000000,11935.000000,4930.00000,15.000100,500001.00000

4. head() in Pandas used to print starting 5 records from the given list

In [79]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0

4. tail() in Pandas used to print Last 5 records from the given list

In [80]:
df.tail()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

### -> Data Selection

##### 1. 1D (series)

In [81]:
df["longitude"] #1D (series)

0      -122.05
1      -118.30
2      -117.81
3      -118.36
4      -119.67
         ...
2995   -119.86
2996   -118.14
2997   -119.70
2998   -117.12
2999   -119.63
Name: longitude, Length: 3000, dtype: float64

##### 2. 2D (Data frames)

In [82]:
df[["longitude","latitude"]]

      longitude  latitude
0       -122.05     37.37
1       -118.30     34.26
2       -117.81     33.78
3       -118.36     33.82
4       -119.67     36.33
...         ...       ...
2995    -119.86     34.42
2996    -118.14     34.06
2997    -119.70     36.30
2998    -117.12     34.10
2999    -119.63     34.42

[3000 rows x 2 columns]

##### 3. iloc(index no.)

In [83]:
df.iloc[8]

longitude               -122.8400
latitude                  38.4000
housing_median_age        15.0000
total_rooms             3080.0000
total_bedrooms           617.0000
population              1446.0000
households               599.0000
median_income              3.6696
median_house_value    194400.0000
Name: 8, dtype: float64

### -> Handling Missing values

In [84]:
df2 = pd.read_excel("/content/sample_data/Data.xlsx")

In [85]:
df2

   User_ID            Name   Age   Join_Date  Monthly_Spend Premium_Member
0     1001     Alice Smith  28.0  2024-01-15          145.2            Yes
1     1002       Bob Jones   NaN  2023-11-22           89.5             No
2     1003   Charlie Brown  42.0  2025-03-05            NaN            Yes
3     1004    David Miller  31.0         NaN          210.0             No
4     1005       Eva Davis   NaN  2024-06-18           55.0            NaN
5     1006    Frank Wilson  55.0  2022-08-30          415.8            Yes
6     1007       Grace Lee  23.0  2025-01-12            NaN             No
7     1008    Henry Taylor   NaN         NaN          125.0             No
8     1009  Isabella Clark  38.0  2023-05-19          305.1            Yes
9     1010     Jack Thomas  47.0  2024-10-01            NaN            NaN

1. Remove all Missing values

In [86]:
df2.dropna()

   User_ID            Name   Age   Join_Date  Monthly_Spend Premium_Member
0     1001     Alice Smith  28.0  2024-01-15          145.2            Yes
5     1006    Frank Wilson  55.0  2022-08-30          415.8            Yes
8     1009  Isabella Clark  38.0  2023-05-19          305.1            Yes

2. Replace Missing values

In [87]:
df2.fillna(value=0)

   User_ID            Name   Age   Join_Date  Monthly_Spend Premium_Member
0     1001     Alice Smith  28.0  2024-01-15          145.2            Yes
1     1002       Bob Jones   0.0  2023-11-22           89.5             No
2     1003   Charlie Brown  42.0  2025-03-05            0.0            Yes
3     1004    David Miller  31.0           0          210.0             No
4     1005       Eva Davis   0.0  2024-06-18           55.0              0
5     1006    Frank Wilson  55.0  2022-08-30          415.8            Yes
6     1007       Grace Lee  23.0  2025-01-12            0.0             No
7     1008    Henry Taylor   0.0           0          125.0             No
8     1009  Isabella Clark  38.0  2023-05-19          305.1            Yes
9     1010     Jack Thomas  47.0  2024-10-01            0.0              0

3. Rename Column Name

In [88]:
df2.rename(columns={"JD":"Join_Date","MD":"Monthly_Spend"},)
df2
df2.fillna(value=0, inplace=True)

In [89]:
def fx(a):
  return a * 2
df2["Increased_spend"]= df2["Monthly_Spend"].apply(fx)

In [90]:
df2

,User_ID,Name,Age,Join_Date,Monthly_Spend,Premium_Member,Increased_spend
0,1001,Alice Smith,28.0,2024-01-15,145.2,Yes,290.4
1,1002,Bob Jones,0.0,2023-11-22,89.5,No,179.0
2,1003,Charlie Brown,42.0,2025-03-05,0.0,Yes,0.0
3,1004,David Miller,31.0,0,210.0,No,420.0
4,1005,Eva Davis,0.0,2024-06-18,55.0,0,110.0
5,1006,Frank Wilson,55.0,2022-08-30,415.8,Yes,831.6
6,1007,Grace Lee,23.0,2025-01-12,0.0,No,0.0
7,1008,Henry Taylor,0.0,0,125.0,No,250.0
8,1009,Isabella Clark,38.0,2023-05-19,305.1,Yes,610.2
9,1010,Jack Thomas,47.0,2024-10-01,0.0,0,0.0

Below code is used to export a copy of an operating file

In [ ]:
df2.to_csv("Data.xlsx/export.csv",index=False)

#### Merging and Concatination

1. Concatination

In [93]:
df1 = pd.DataFrame({"Names": ["Mohammed Affan", "Shaik Sahil", "Mohammed Faizaan Ali Khan"], 'Marks': [32, 33, 35]})

df1

                       Names  Marks
0             Mohammed Affan     32
1                Shaik Sahil     33
2  Mohammed Faizaan Ali Khan     35

In [95]:
df2 = pd.DataFrame({"Names": ["Mohammed Abdul Adeeb", "Shaik Cezan", "syed waseem"], 'Marks': [38, 35, 34]})
df2

                  Names  Marks
0  Mohammed Abdul Adeeb     38
1           Shaik Cezan     35
2           syed waseem     34

In [97]:
pd.concat([df1,df2])

                       Names  Marks
0             Mohammed Affan     32
1                Shaik Sahil     33
2  Mohammed Faizaan Ali Khan     35
0       Mohammed Abdul Adeeb     38
1                Shaik Cezan     35
2                syed waseem     34

2. Merging

In [98]:
df1 = pd.DataFrame({"Names": ["Mohammed Affan", "Shaik Sahil", "Mohammed Faizaan Ali Khan"], 'Marks': [32, 33, 35]})

df1

                       Names  Marks
0             Mohammed Affan     32
1                Shaik Sahil     33
2  Mohammed Faizaan Ali Khan     35

In [99]:
df2 = pd.DataFrame({"Names": ["Mohammed Affan", "Shaik Sahil", "Mohammed Faizaan Ali Khan"], 'RollNo': [504, 507, 505]})

df2

                       Names  RollNo
0             Mohammed Affan     504
1                Shaik Sahil     507
2  Mohammed Faizaan Ali Khan     505

In [100]:
pd.merge(df1,df2,on="Names")

                       Names  Marks  RollNo
0             Mohammed Affan     32     504
1                Shaik Sahil     33     507
2  Mohammed Faizaan Ali Khan     35     505